name: Execute pytest for Git Server and Client on Docker Automation Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest --html=report.html --self-contained-html

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: report.html

      - name: Generate GitHub Dashboard
        run: |
          echo "### Git Test Results :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "✅ Tests Passed: $(grep -oP '(?<=<span class="passed">)[^<]+' report.html | sed 's/ Passed,//' | awk '{print $1}')" >> $GITHUB_STEP_SUMMARY
          echo "❌ Tests Failed: $(grep -oP '(?<=<span class="failed">)[^<]+' report.html | sed 's/ Failed,//' | awk '{print $1}')" >> $GITHUB_STEP_SUMMARY
          echo "[🔍 View Full Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $GITHUB_STEP_SUMMARY
